name: Demo workflow

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
    workflow_dispatch:
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello Demo
        run: echo "Hello Demo"
        shell: bash
  middle:
    runs-on: ubuntu-latest
    steps:
      - name: End
        run: echo "Middle Demo File"
        shell: bash
  end:
    runs-on: ubuntu-latest
    steps:
      - name: End
        run: echo "End Demo File"
        shell: bash